package com.example.kmptemplate.firebase.crashlytics

import com.google.firebase.crashlytics.FirebaseCrashlytics

actual class CrashReporter actual constructor() {

    /**
     * Firebase auto-initialises from resources generated by the google-services plugin. That
     * plugin is only applied when google-services.json exists, so without it this throws and
     * the reporter degrades to a no-op rather than taking the app down.
     */
    private val crashlytics: FirebaseCrashlytics? = runCatching {
        FirebaseCrashlytics.getInstance()
    }.getOrNull()

    actual val isAvailable: Boolean get() = crashlytics != null

    actual fun log(message: String) {
        crashlytics?.log(message)
    }

    actual fun recordException(throwable: Throwable) {
        crashlytics?.recordException(throwable)
    }

    actual fun setUserId(userId: String?) {
        crashlytics?.setUserId(userId ?: "")
    }
}
